// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersistentFlightContext;

namespace PersistentFlightContext.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20180609112325_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("Boerman.FlightAnalysis.Models.FlightMetadata", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Aircraft");

                    b.Property<short>("ArrivalHeading");

                    b.Property<bool?>("ArrivalInfoFound");

                    b.Property<string>("ArrivalLocation");

                    b.Property<short>("DepartureHeading");

                    b.Property<bool?>("DepartureInfoFound");

                    b.Property<string>("DepartureLocation");

                    b.Property<DateTime?>("EndTime");

                    b.Property<DateTime?>("LastSeen");

                    b.Property<DateTime?>("StartTime");

                    b.HasKey("Id");

                    b.ToTable("Flights");
                });
#pragma warning restore 612, 618
        }
    }
}
